Corrected handling of path in function findImageHeight, that caused error on Windows (XP):
File "c:\SAP\scripty\pytesseracttrainer\pyTesseractTrainer.py", line 207, in findImageHeight
    height = int(f.readline())
ValueError: invalid literal for int() with base 10: ''